### ISSUE TITLE
ROS2 Foxy Upgrade

### ISSUE THREAD

**Issue by stonier** [kobuki-base/kobuki_ros#6]
* [x] Keyop - upgrade &rarr; #3 
* [x] Node - upgrade &rarr; #9
* [ ] Keyop - testing & integration (replicate & verify ye olde `keyop.launch` and `safe_keyop.launch`)
* [ ] Keyop - documentation (see also #5)
* [ ] Deprecate use of `ecl::LegacyPose2D` (refer to #11)
* [ ] Node - refactor some subset of parameters to be dynamic
* [ ] Node - documentation
* [ ] License rearrangment
* [ ] Version bump to `1.0.0`
* [ ] Release

**Comment by stonier** [comment]
Mini-apps, testing and integration launchers in a separate package? That would keep `kobuki_node` dependencies slim.
